# Generated by Django 5.2.8 on 2025-12-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('INVESTOR', 'Investor')], max_length=20, null=True),
        ),
    ]
