# Generated by Django 5.2.8 on 2025-12-05 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customerorder_customerprofile_deviceinstance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.room'),
        ),
        migrations.CreateModel(
            name='OrderRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_rooms', to='core.customerorder')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_room_relations', to='core.room')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_order_rooms',
            },
        ),
        migrations.AddField(
            model_name='customerorder',
            name='rooms',
            field=models.ManyToManyField(related_name='order_rooms', through='core.OrderRoom', to='core.room'),
        ),
        migrations.CreateModel(
            name='OrderRoomDeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_room_device_type_relations', to='core.devicetype')),
                ('order_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_room_device_types', to='core.orderroom')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_order_room_device_types',
                'unique_together': {('order_room', 'device_type')},
            },
        ),
        migrations.AddField(
            model_name='orderroom',
            name='device_types',
            field=models.ManyToManyField(related_name='order_room_device_types', through='core.OrderRoomDeviceType', to='core.devicetype'),
        ),
        migrations.AlterUniqueTogether(
            name='orderroom',
            unique_together={('order', 'room')},
        ),
    ]
