# Generated by Django 5.2.8 on 2025-12-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodels',
            name='type',
            field=models.CharField(choices=[('purifier', 'Air Purifier'), ('aroma', 'Aroma'), ('humidifier', 'Air Humidifier'), ('sensor', 'Air Quality Sensor'), ('conditioner', 'Air Conditioner')], max_length=255),
        ),
    ]
