# Generated by Django 5.2.8 on 2025-12-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_devicemodels_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodels',
            name='type',
            field=models.CharField(choices=[('sensor', 'Air Quality Sensor'), ('humidifier', 'Air Humidifier'), ('purifier', 'Air Purifier'), ('conditioner', 'Air Conditioner'), ('aroma', 'Aroma')], max_length=255),
        ),
    ]
