# Generated by Django 5.2.8 on 2025-12-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_devicemodels_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodels',
            name='type',
            field=models.CharField(choices=[('aroma', 'Aroma'), ('purifier', 'Air Purifier'), ('sensor', 'Air Quality Sensor'), ('conditioner', 'Air Conditioner'), ('humidifier', 'Air Humidifier')], max_length=255),
        ),
    ]
