# Generated by Django 5.2.8 on 2025-12-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_devicemodels_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodels',
            name='type',
            field=models.CharField(choices=[('purifier', 'Air Purifier'), ('sensor', 'Air Quality Sensor'), ('aroma', 'Aroma'), ('humidifier', 'Air Humidifier'), ('conditioner', 'Air Conditioner')], max_length=255),
        ),
    ]
