# Generated by Django 5.2.8 on 2025-12-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_devicemodels_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodels',
            name='type',
            field=models.CharField(choices=[('conditioner', 'Air Conditioner'), ('purifier', 'Air Purifier'), ('humidifier', 'Air Humidifier'), ('sensor', 'Air Quality Sensor'), ('aroma', 'Aroma')], max_length=255),
        ),
    ]
